apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: InfluxDB
    uid: P951FEA4DE68E13C5
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: prometheus
    jsonData:
      httpMode: GET
